version: '3'

services:
  db:
    image: 'postgres'
    container_name: 'database'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: digisign