# Generated by Django 3.2.7 on 2021-09-15 14:07

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date/time this object was created.', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date/time this object was last updated.', verbose_name='modified')),
                ('modified_by', models.CharField(blank=True, help_text='Optionally identifies who last updated the object.', max_length=255)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('deleted', models.DateTimeField(blank=True, help_text='Date/time this object was deleted.', null=True, verbose_name='deleted')),
                ('name', models.CharField(max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('modules', models.ManyToManyField(blank=True, related_name='access_groups', to='modules.Module', verbose_name='modules')),
            ],
            options={
                'db_table': 'access_group',
                'ordering': ('name',),
            },
        ),
    ]
