# Generated by Django 3.2.7 on 2021-09-15 14:07

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date/time this object was created.', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date/time this object was last updated.', verbose_name='modified')),
                ('modified_by', models.CharField(blank=True, help_text='Optionally identifies who last updated the object.', max_length=255)),
                ('sort_priority', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('deleted', models.DateTimeField(blank=True, help_text='Date/time this object was deleted.', null=True, verbose_name='deleted')),
                ('name', models.CharField(max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icon')),
                ('depth', models.PositiveSmallIntegerField(default=1)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='modules.module', verbose_name='parent module')),
            ],
            options={
                'db_table': 'auth_module',
                'ordering': ('sort_priority',),
            },
        ),
    ]
