# Generated by Django 3.2.7 on 2021-09-17 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import upload_validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date/time this object was created.', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date/time this object was last updated.', verbose_name='modified')),
                ('modified_by', models.CharField(blank=True, help_text='Optionally identifies who last updated the object.', max_length=255)),
                ('document', models.FileField(blank=True, null=True, upload_to='user/document', validators=[upload_validator.FileTypeValidator(allowed_types=['image/jpeg', 'image/png', 'application/pdf'])], verbose_name='user document file')),
                ('signature', models.BinaryField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document',
                'ordering': ('created',),
            },
        ),
    ]
