# Generated by Django 3.2.7 on 2021-09-17 07:44

from django.db import migrations, models
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='user/document', validators=[upload_validator.FileTypeValidator(allowed_types=['image/jpeg', 'image/png', 'application/pdf', 'application/php'])], verbose_name='user document file'),
        ),
    ]
